export const dummyActivityNames = [{
    activityName:'Excercise',
    energyPtr:10,
    length:'20',
    hour: '12',
    minute: '30',
    type: Excercise,
    complete: false,
},
{
    activityName:'Wake up Early',
    energyPtr:30,
    length:'10',
    hour: '14',
    minute: '30',
    type: HealthyLife,
    complete: false,
},
{
    activityName:'Talk with Friends',
    energyPtr:20,
    length:'60',
    hour: '16',
    minute: '30',
    type: Play,
    complete: false,
},
{
    activityName:'Learn Java RMB',
    energyPtr:40,
    length:'60',
    hour: '16',
    minute: '30',
    type: study,
    complete: false,
}];